export const bills = [
  {
    id: "abc123",
    name: "Luz",
    categoryId: "utilities",
    dueDay: 25,
    amount: 120.5,
    createdById: "user1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "def456",
    name: "Água",
    categoryId: "utilities",
    dueDay: 10,
    amount: 65.0,
    createdById: "user2",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "ghi789",
    name: "Aluguel",
    categoryId: "home",
    dueDay: 1,
    amount: 800.0,
    createdById: "user1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "jkl101112",
    name: "Internet",
    categoryId: "utilities",
    dueDay: 22,
    amount: 80.25,
    createdById: "user2",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "mno131415",
    name: "Compras",
    categoryId: "food",
    dueDay: 18,
    amount: 250.75,
    createdById: "user1",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
